### ISSUE TITLE
Issues in running test 

### ISSUE THREAD

**Issue by akure** [TxCorpi0x/nameservice#4]
Hi,

I followed below steps in my home directory.

/home/ubuntu/
cd github/
git clone https://github.com/vjdmhd/nameservice.git
cd nameservice

I ran, startport serve, it works.

For unit test :
pwd: /home/ubuntu/github/nameservice

ubuntu@ip-10-0-1-38:~/github/nameservice$ go test
PASS
ok  	github.com/vjdmhd/nameservice	0.051s

**How do I know what all test cases has run?**
**Add some command lines outputs for each test cases?**

ubuntu@ip-10-0-1-38:~/github/nameservice$ go test handler_test.go 

command-line-arguments [command-line-arguments.test]
./handler_test.go:24:41: undefined: CreateTestHandler
FAIL	command-line-arguments [build failed]
FAIL
 
**Why go test handler_test.go  is failing in my setting ? Can you figure it out and fix it? **

**Comment by vjdmhd** [comment]
Hi there,

For the first question, I will do it in coming hours,

For the second one:
according to these references:
[Go testing](https://golang.org/pkg/testing/)
[Stackoverflow](https://stackoverflow.com/questions/14723229/go-test-cant-find-function-in-a-same-package)

appropriate type of running tests is by 
```
go test
```
it covers any file name trailing "*test.go" so "test_common.go" will not imported automatically, 
But if you are willing to run by file name you can issue this:
```
go test test_common.go handler_test.go
```
all of dependencies (even if the same module) should be provided in the command line arguments.

**Comment by akure** [comment]
I added some fmt.Printfs in the Test functions of handler_test.go

I think they are not getting called.

ubuntu@ip-10-0-1-38:~/github/nameservice$ go test handler_test.go test_common.go 
ok  	command-line-arguments	0.052s

**Comment by akure** [comment]
go test -v options works for it.

**Comment by TxCorpi0x** [comment]
Instead of  "fmt.Printfs" it's better to use "log.t"  and the "-v" flag makes test module to show logs even if the test is passed.
